-- MySQL Script generated by MySQL Workbench
-- mié 06 sep 2023 22:39:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(90) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `Rol` INT NULL,
  `Telefono` VARCHAR(30) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cursos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(450) NULL,
  `Nivel` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inscripciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inscripciones` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDUsuario` INT NOT NULL,
  `IDCurso` INT NOT NULL,
  `Puntuacion` INT ZEROFILL NULL,
  `Favorito` TINYINT ZEROFILL NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idInscripciones_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Inscripciones_1_idx` (`IDUsuario` ASC) VISIBLE,
  INDEX `fk_Inscripciones_2_idx` (`IDCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Inscripciones_1`
    FOREIGN KEY (`IDUsuario`)
    REFERENCES `mydb`.`Usuarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripciones_2`
    FOREIGN KEY (`IDCurso`)
    REFERENCES `mydb`.`Cursos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorias` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorizaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorizaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorizaciones` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDCurso` INT NOT NULL,
  `IDCategoria` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Categorizaciones_1_idx` (`IDCategoria` ASC) VISIBLE,
  INDEX `fk_Categorizaciones_2_idx` (`IDCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Categorizaciones_1`
    FOREIGN KEY (`IDCategoria`)
    REFERENCES `mydb`.`Categorias` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categorizaciones_2`
    FOREIGN KEY (`IDCurso`)
    REFERENCES `mydb`.`Cursos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lecciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lecciones` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Contenido` VARCHAR(450) NULL,
  `Duracion` INT ZEROFILL NOT NULL,
  `Orden` INT ZEROFILL NOT NULL,
  `IDCurso` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Lecciones_1_idx` (`IDCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Lecciones_1`
    FOREIGN KEY (`IDCurso`)
    REFERENCES `mydb`.`Cursos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
