name: Android CI

on:
  pull_request:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: mkdir -p build && ./gradlew build --stacktrace --info 2> build/results.txt
      continue-on-error: true
      id: build

    - name: Get build results
      if: steps.build.outcome == 'failure'
      run: echo "BUILD_RESULT=$(sed ':a;N;$!ba;s/\n/ /g' build/results.txt)" >> $GITHUB_ENV
      continue-on-error: true

    - name: Create PR comment
      if: steps.build.outcome == 'failure'
      uses: actions/github-script@v4
      with:
        script: |
          if (!context.issue) {
            console.log('No existe context.issue');
            return;
          }
          
          const buildResult = process.env.BUILD_RESULT.replace(/(?:\r\n|\r|\n)/g, ' ');
          const issueComment = 'El Build fallo con el siguiente error: \n```\n' + buildResult + '\n```';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: issueComment
          });
    
